### ISSUE TITLE
Pressing issues: What are we showing here?

### ISSUE THREAD

**Issue by mklasen** [MindblownHQ/shop-health-roadmap#295]
Have a good look at what we're showing here - is this valuable? is this what we want to show?

~We can close this issue when either:~
~- We're all good with what we show here and how we show it~
~- We're good for now but want to improve later (requires new issue)~

Update:
- New issue created for initial release: https://github.com/MindblownHQ/shop-health/issues/320
- This issue is moved to the improved release milestone

**Comment by lucprincen** [comment]
Was fixed in #320 .
Closing this here.
